image: docker:latest

stages: 
  - build
  - deploy

services:
  - docker:dind
  - node:10
    
build:
  stage: build
  image: node:10
  script:
  - if [ -e node_modules ] ; then echo exists; else mkdir node_modules; fi
  #- docker run --rm -v `pwd`:/app -w /app node:10 bash -c "npm install && npm run build"
  - npm install
  - npm prune --prod
  - npm run build
  artifacts:
    paths:
      - build/
  only:
  - develop # or master, the branch you want to publish

deploy:
  stage: deploy
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build --rm -f Dockerfile -t registry.gitlab.com/collinear/tributary/$CI_PROJECT_NAME:latest .
  - docker push registry.gitlab.com/collinear/tributary/$CI_PROJECT_NAME:latest
  only:
  - ci # or master, the branch you want to publish

publish-pages:
  stage: deploy
  script: 
  - cp -r build public
  only:
  - develop

cache:
  paths:
  - node_modules
