image: docker:latest

stages: 
  - build
  - deploy
  - publish

# services:
  # - docker:dind
  # - node:10
    
build:
  stage: build
  image: node:10
  script:
  - if [ -e node_modules ] ; then echo exists; else mkdir node_modules; fi
  - npm install
  - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build --rm -f docker_deploy/Dockerfile -t registry.gitlab.com/collinear/tributary/$CI_PROJECT_NAME:latest .
  - docker push registry.gitlab.com/collinear/tributary/$CI_PROJECT_NAME:latest
  only:
  - develop # or master, the branch you want to publish

# pages:
#   stage: publish
#   script: 
#   - cp -r build public
#   artifacts:
#     paths:
#     - public # mandatory, other folder won't work
#   only:
#     - develop

cache:
  paths:
  - node_modules
